### ISSUE TITLE
Printing Python dictionary with CumulusLogger results in KeyError:

### ISSUE THREAD

**Issue by camposeddie** [nasa/cumulus-orca#109]
**Context:**
During testing of ORCA file retrieval GHRC ran into an error which was first presented as a KeyError, but the root was later found to be an issue with the CumulusLogger package's inability to print Python dictionaries within the message string. This was identified at https://github.com/nasa/cumulus-orca/blob/master/tasks/request_files/request_files.py#L243 and will likely also occur in develop branch: https://github.com/nasa/cumulus-orca/blob/develop/tasks/request_files/request_files.py#L382-L384

**Problem:**
ORCA is using the CumulusLogger package for logging errors; however, CumulusLogger uses str().format to parse the message input which will error out with a KeyError if passed a Python dictionary within an f string.

**How to replicate:**
```
from cumulus_logger import CumulusLogger
LOGGER = CumulusLogger()
test_dictionary = {'test': "dictionary"}
LOGGER.error(f"{test_dictionary}") # will error out
LOGGER.error(f"Test dict within string {test_dictionary}") # will error out
LOGGER.error(test_dictionary) # will not error out, but may be confusing as it merges the parameter JSON with the logger JSON
```

**Comment by bhazuka** [comment]
This issue has been fixed in version 3.0 of the software through various commits.
