### ISSUE TITLE
AWS Secrets Manager scheduled delay causing errors in deployments

### ISSUE THREAD

**Issue by camposeddie** [nasa/cumulus-orca#114]
**Context**
With ORCA db secrets, AWS secrets are scheduled for deletion rather than force deleted immediately.
**Problem**
This is causing the following errors within our CI/CD build when updates are made:
```
Error: error creating Secrets Manager Secret: InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion.
on .terraform/modules/ghrc_orca/modules/rds/main.tf line 53, in resource "aws_secretsmanager_secret" "drdb-admin-pass":
  53: resource "aws_secretsmanager_secret" "drdb-admin-pass" 
  
Error: error creating Secrets Manager Secret: InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion.
on .terraform/modules/ghrc_orca/modules/rds/main.tf line 64, in resource "aws_secretsmanager_secret" "drdb-user-pass":
  64: resource "aws_secretsmanager_secret" "drdb-user-pass" 
  
Error: error creating Secrets Manager Secret: InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion.
on .terraform/modules/ghrc_orca/modules/rds/main.tf line 75, in resource "aws_secretsmanager_secret" "drdb-host":
  75: resource "aws_secretsmanager_secret" "drdb-host" 
```

Optimally, these values would be deleted immediately rather than being scheduled for deletion or there would be a way to rename the secret value names so that we could circumvent the error; however, currently, many of these values are hardcoded into ORCA source.

**Comment by bhazuka** [comment]
This has been fixed in version 3.0 of the software and was part of this commit https://github.com/nasa/cumulus-orca/commit/94eb0bd150c921aeff7c1fab32dc88567d9c70ab 

The AWS secret keys now how have a recovery window of 0 `recovery_window_in_days = 0`
